name: qcb
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - absl-py=1.4.0=pyhd8ed1ab_0
  - arrow-cpp=11.0.0=h374c478_2
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.3=py310h06a4308_0
  - aws-c-common=0.6.8=h5eee18b_1
  - aws-c-event-stream=0.1.6=h6a678d5_6
  - aws-checksums=0.1.11=h5eee18b_2
  - aws-sdk-cpp=1.8.185=h721c034_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boost-cpp=1.73.0=h7f8727e_12
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.08.22=h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.1.2=py310h06a4308_0
  - contextlib2=21.6.0=pyhd8ed1ab_0
  - cryptography=41.0.2=py310h22a60cf_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gflags=2.2.2=he6710b0_0
  - giflib=5.2.1=h5eee18b_3
  - glog=0.5.0=h2531618_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - icu=58.2=he6710b0_3
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - ipykernel=6.25.0=py310h2f386ee_0
  - ipython=8.12.2=py310h06a4308_0
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.1.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.1.0=py310h06a4308_0
  - jupyter_core=5.3.0=py310h06a4308_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libboost=1.73.0=h28710b8_12
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.7.1.12=0
  - libcurand=10.3.3.129=0
  - libcurl=8.2.1=h251f7ec_0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.1.0=he5830b7_0
  - libgomp=13.1.0=he5830b7_0
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnghttp2=1.52.0=h2d74bed_1
  - libnpp=11.7.4.75=0
  - libnsl=2.0.0=h7f98852_0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.4.0=hecacb30_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.6=py310h1128e8f_1
  - mkl_random=1.2.2=py310h1128e8f_1
  - ml-collections=0.1.1=pyhd8ed1ab_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py310h06a4308_0
  - numexpr=2.8.4=py310h85018f9_1
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.11=h7f8727e_2
  - orc=1.7.4=hb3bc3d3_1
  - packaging=24.1=py310h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py310h6a678d5_0
  - pip=23.2.1=pyhd8ed1ab_0
  - platformdirs=3.10.0=py310h06a4308_0
  - prompt-toolkit=3.0.43=py310h06a4308_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py310h06a4308_1
  - pyopenssl=23.2.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.6=ha86cf86_0_cpython
  - python_abi=3.10=3_cp310
  - pytorch=2.0.0=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pyzmq=25.1.0=py310h6a678d5_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - responses=0.13.3=pyhd3eb1b0_0
  - setuptools=72.1.0=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=h295c915_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.11.1=py310h06a4308_0
  - tbb=2021.6.0=hdb19cb5_1
  - tk=8.6.12=h1ccaba5_0
  - torchtriton=2.0.0=py310
  - torchvision=0.15.0=py310_cu117
  - tornado=6.4.1=py310h5eee18b_0
  - traitlets=5.7.1=py310h06a4308_0
  - utf8proc=2.6.1=h27cfd23_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - accelerate==0.33.0
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anthropic==0.34.2
      - anyio==4.6.0
      - attrs==24.2.0
      - cachetools==5.5.0
      - certifi==2024.8.30
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==3.0.0
      - dill==0.3.8
      - distro==1.9.0
      - evaluate==0.4.3
      - exceptiongroup==1.2.2
      - fastchat==0.1.0
      - filelock==3.16.1
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.20.0
      - google-api-python-client==2.147.0
      - google-auth==2.35.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.2
      - googleapis-common-protos==1.65.0
      - grpcio==1.66.1
      - grpcio-status==1.66.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httpx==0.27.2
      - huggingface-hub==0.25.0
      - idna==3.10
      - jiter==0.5.0
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - matplotlib==3.9.2
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nltk==3.9.1
      - openai==1.50.2
      - pandas==2.2.3
      - patsy==0.5.6
      - proto-plus==1.24.0
      - protobuf==5.28.0
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.7.24
      - requests==2.32.3
      - rsa==4.9
      - safetensors==0.4.4
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - sniffio==1.3.1
      - statsmodels==0.14.2
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.19.1
      - tqdm==4.66.5
      - transformers==4.44.1
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - uritemplate==4.1.1
      - urllib3==2.2.3
      - xxhash==3.5.0
      - yarl==1.11.1